# curricula.py
from typing import Dict, Any

class DetailedCurricula:
    @staticmethod
    def get_curricula() -> Dict[str, Dict[str, Any]]:
        return {
            # Programming & Tech
            "dsa": {
                "topics": ["Arrays and String Manipulation", "Two Pointers and Sliding Window", "Linked Lists Operations", "Stacks and Queues", "Recursion and Backtracking", "Binary Trees Fundamentals", "Binary Search Trees", "Tree Traversals", "Heaps and Priority Queues", "Hash Tables", "Graph Representation", "Graph Traversals (BFS/DFS)", "Shortest Path Algorithms", "Dynamic Programming Basics", "1D DP Problems", "2D DP Problems", "Advanced DP Patterns", "Greedy Algorithms", "Bit Manipulation", "Trie Data Structure", "Union Find", "Advanced Graph Algorithms", "String Algorithms", "Mathematical Algorithms", "System Design"],
                "practical_tasks": ["Solve 3 easy array problems on LeetCode focusing on two-pointer technique", "Implement a hash table from scratch using separate chaining", "Build a binary search tree with insert, delete, and search operations", "Create a graph class and implement BFS/DFS traversal algorithms", "Solve the classic 0/1 Knapsack problem using dynamic programming", "Implement Dijkstra's algorithm for shortest path finding", "Code a trie data structure for autocomplete functionality", "Practice 5 medium-level recursion problems with backtracking", "Build a min-heap and max-heap with heapify operations", "Solve string matching problems using KMP algorithm"],
                "projects": ["Build a simple text editor with undo/redo using stacks", "Create a maze solver using BFS algorithm", "Implement a basic compiler's symbol table using hash tables", "Build a family tree application using tree data structures"]
            },
            "react": {
                "topics": ["React Environment Setup", "JSX Syntax and Components", "Props and State Management", "Event Handling", "Conditional Rendering", "Lists and Keys", "Forms and Inputs", "Component Lifecycle", "useEffect Hook", "useState Hook", "Custom Hooks", "Context API", "React Router", "State Management with Redux", "HTTP Requests and APIs", "Error Boundaries", "Performance Optimization", "Code Splitting", "Testing with Jest", "Styled Components", "Material-UI Integration", "TypeScript with React", "Next.js Fundamentals", "Server-side Rendering", "Static Site Generation"],
                "practical_tasks": ["Build a counter app with increment/decrement functionality using useState", "Create a todo list with add, delete, and mark complete features", "Implement a weather app that fetches data from OpenWeatherMap API", "Build a product catalog with search and filter functionality", "Create a multi-step form with validation and progress indicator", "Develop a shopping cart with add/remove items and total calculation", "Build a blog interface with post creation and comment system", "Implement user authentication with login/logout functionality", "Create a dashboard with charts using recharts library", "Build a real-time chat interface using WebSocket connection"],
                "projects": ["Build a complete e-commerce storefront with product listing and checkout", "Create a social media dashboard with post feeds and interactions", "Develop a project management tool with task boards and team collaboration", "Build a personal finance tracker with expense categorization and reports"]
            },
            "python": {
                "topics": ["Python Environment Setup", "Variables and Data Types", "Control Structures", "Functions and Scope", "Lists and Tuples", "Dictionaries and Sets", "String Methods", "File Handling", "Exception Handling", "Object-Oriented Programming", "Classes and Objects", "Inheritance and Polymorphism", "Modules and Packages", "Lambda Functions", "Decorators", "Generators and Iterators", "Regular Expressions", "Working with APIs", "Database Integration", "Web Scraping", "GUI Development", "Testing with pytest", "Virtual Environments", "Deployment"],
                "practical_tasks": ["Build a personal expense tracker that reads/writes CSV files", "Create a web scraper for job listings using BeautifulSoup", "Develop a password manager with encryption using cryptography library", "Build a REST API for a bookstore using Flask and SQLAlchemy", "Create a data analysis script for sales data using pandas", "Implement a file organizer that sorts files by type and date", "Build a weather CLI app that fetches data from weather APIs", "Create a basic chatbot using natural language processing", "Develop a stock price analyzer with visualization using matplotlib", "Build a automated email sender for newsletters using smtplib"],
                "projects": ["Create a complete blog system with user management and post CRUD operations", "Build a inventory management system for small businesses", "Develop a machine learning model for house price prediction", "Create a social media automation tool for content scheduling"]
            },
            
            # Languages
            "hindi": {
                "topics": ["Devanagari Script Basics", "Vowels (स्वर) and Consonants (व्यंजन)", "Matras and Conjunct Characters", "Basic Vocabulary - Family and Body Parts", "Numbers and Time", "Common Verbs and Actions", "Present Tense Conjugation", "Past Tense Formation", "Future Tense Usage", "Questions and Negation", "Postpositions and Sentence Structure", "Formal vs Informal Speech", "Cultural Context and Idioms", "Reading Simple Stories", "Conversation Practice", "Advanced Grammar Rules", "Literary Hindi", "Regional Variations", "Business Hindi", "Hindi Cinema and Culture"],
                "practical_tasks": ["Practice writing 50 Devanagari characters with proper stroke order", "Learn and memorize 20 family relationship terms in Hindi", "Create flashcards for 100 most common Hindi words with pronunciation", "Practice conjugating 10 essential verbs in present tense", "Have a 5-minute conversation about daily routine in Hindi", "Read a simple Hindi children's story and summarize it", "Watch a Bollywood movie scene and identify 20 new vocabulary words", "Write a short paragraph about your hobbies in Hindi", "Practice listening to Hindi news for 10 minutes and note key points", "Compose and sing a simple Hindi song or poem"],
                "projects": ["Create a Hindi vocabulary journal with 500+ words", "Record yourself telling your life story in Hindi (10 minutes)", "Write and illustrate a children's book in Hindi", "Start a Hindi language learning blog or vlog"]
            },
            "english": {
                "topics": ["Grammar Fundamentals", "Parts of Speech", "Sentence Structure", "Tenses and Verb Forms", "Vocabulary Building", "Reading Comprehension", "Writing Skills", "Speaking and Pronunciation", "Listening Skills", "Idioms and Phrases", "Formal vs Informal English", "Business English", "Academic Writing", "Creative Writing", "Public Speaking", "Debate and Discussion", "Literature Appreciation", "Poetry and Prose", "Critical Thinking", "Communication Skills"],
                "practical_tasks": ["Read one English article daily and summarize key points", "Practice pronunciation using tongue twisters and difficult words", "Write a 500-word essay on a current topic", "Join online English conversation groups for 30 minutes", "Learn 10 new vocabulary words daily with example sentences", "Record yourself reading a news article and analyze pronunciation", "Write business emails for different scenarios", "Practice giving 5-minute presentations on various topics", "Complete grammar exercises focusing on common mistakes", "Watch English movies with subtitles and note new expressions"],
                "projects": ["Write a short story or novel chapter", "Create a podcast episode in English", "Deliver a 15-minute presentation on your expertise area", "Start an English language blog"]
            },
            
            # Creative Arts
            "photography": {
                "topics": ["Camera Basics and Types", "Exposure Triangle (Aperture, Shutter, ISO)", "Composition Rules and Techniques", "Lighting Fundamentals", "Portrait Photography", "Landscape Photography", "Street Photography", "Macro Photography", "Night Photography", "Color Theory in Photography", "Black and White Photography", "Post-Processing Basics", "Adobe Lightroom Essentials", "Photoshop for Photographers", "Equipment and Gear", "Photo Storytelling", "Commercial Photography", "Wedding Photography", "Photography Business", "Portfolio Development"],
                "practical_tasks": ["Take 50 photos practicing rule of thirds and leading lines", "Shoot a portrait session using natural light only", "Create a photo series documenting a day in your neighborhood", "Practice manual mode photography in different lighting conditions", "Edit 20 RAW photos using Lightroom with consistent style", "Shoot a golden hour landscape session focusing on composition", "Take macro photos of everyday objects using extension tubes or close-up filters", "Create a black and white photo essay on a social theme", "Practice long exposure photography for water and cloud movement", "Photograph the same subject in 10 different ways"],
                "projects": ["Create a 30-photo portfolio showcasing different styles", "Document a local event or festival through photography", "Start a photography challenge (365 project or weekly themes)", "Organize and exhibit your work in a local gallery or online platform"]
            },
            "music": {
                "topics": ["Music Theory Basics", "Notes, Scales, and Keys", "Rhythm and Time Signatures", "Intervals and Chords", "Melody and Harmony", "Instrument Techniques", "Ear Training", "Sight Reading", "Composition Basics", "Song Structure", "Recording Techniques", "Music Production", "Performance Skills", "Stage Presence", "Music Genres and Styles", "Music History", "Improvisation", "Ensemble Playing", "Music Business", "Teaching Music"],
                "practical_tasks": ["Practice scales daily for 15 minutes on your chosen instrument", "Learn to play 3 songs in different genres completely", "Compose a simple 8-bar melody using pentatonic scale", "Record yourself playing and analyze rhythm accuracy", "Practice sight-reading simple melodies for 10 minutes daily", "Jam with other musicians (online or in-person) once per week", "Learn 10 basic chord progressions and their variations", "Write lyrics for an original song", "Practice ear training with interval recognition exercises", "Perform one song publicly (open mic, video, or for friends)"],
                "projects": ["Compose and record an original song from start to finish", "Learn an entire album by your favorite artist", "Start a band or collaborate with other musicians", "Create a music teaching curriculum for beginners"]
            },
            
            # Exam Preparation
            "gate": {
                "topics": ["GATE Exam Pattern and Syllabus", "Engineering Mathematics", "General Aptitude", "Core Subject Fundamentals", "Previous Year Questions Analysis", "Time Management Strategies", "Mock Test Practice", "Weak Area Identification", "Formula Sheets Creation", "Numerical Problem Solving", "Theory Questions Mastery", "Calculator Usage Optimization", "Stress Management", "Revision Strategies", "Online Test Practice", "Answer Writing Techniques", "Negative Marking Strategies", "Last Month Preparation", "Exam Day Guidelines", "Result Analysis"],
                "practical_tasks": ["Solve 50 previous year GATE questions from each major topic", "Take a full-length mock test weekly and analyze performance", "Create formula sheets for Engineering Mathematics and core subjects", "Practice numerical problems with time constraints (2 minutes per problem)", "Solve 20 general aptitude questions daily", "Review and analyze mistakes from previous tests", "Practice calculator usage for complex calculations under time pressure", "Study one complete topic daily with theory and numerical problems", "Create and practice from your own question bank", "Join online test series and compete with other aspirants"],
                "projects": ["Create a comprehensive study plan with daily targets", "Develop a question bank with solutions for difficult topics", "Mentor junior students preparing for GATE", "Document your complete GATE preparation journey"]
            },
            "jee": {
                "topics": ["JEE Main and Advanced Pattern", "Physics Concepts and Applications", "Chemistry Theory and Numericals", "Mathematics Problem Solving", "Organic Chemistry Mechanisms", "Inorganic Chemistry Facts", "Calculus and Coordinate Geometry", "Mechanics and Thermodynamics", "Electrochemistry and Solutions", "Trigonometry and Complex Numbers", "Modern Physics", "Previous Year Analysis", "Mock Test Strategy", "Time Management", "Error Analysis", "Formula Memorization", "Conceptual Clarity", "Problem-Solving Speed", "Exam Psychology", "Result Analysis"],
                "practical_tasks": ["Solve 30 JEE problems daily (10 from each subject)", "Take subject-wise tests weekly and analyze weak areas", "Memorize important formulas using spaced repetition", "Practice drawing chemical structures and mechanisms quickly", "Solve complete physics numericals with proper steps", "Review NCERT textbooks and solve all exercises", "Practice mental math and approximation techniques", "Create and solve your own problems for difficult concepts", "Time yourself while solving previous year papers", "Teach concepts to classmates or younger students"],
                "projects": ["Create a comprehensive formula book with derivations", "Develop a peer study group with structured learning", "Document common mistakes and their solutions", "Create video explanations for difficult concepts"]
            },
            "upsc": {
                "topics": ["UPSC Syllabus and Exam Pattern", "Current Affairs and News Analysis", "Indian Polity and Constitution", "Indian Economy and Budget", "Geography - Physical and Human", "Indian History - Ancient to Modern", "Science and Technology Updates", "Environment and Ecology", "International Relations", "Ethics and Integrity", "Essay Writing Skills", "Answer Writing Practice", "Prelims Test Practice", "Mains Answer Structure", "Interview Preparation", "Optional Subject Mastery", "Public Administration", "Sociology", "Literature", "Medical Science"],
                "practical_tasks": ["Read 3 newspapers daily and create current affairs notes", "Write one 250-word essay daily on diverse topics", "Practice 100 prelims questions daily from different subjects", "Analyze and answer 5 mains questions weekly", "Study one complete topic from NCERT daily", "Create mind maps for complex topics like Indian economy", "Practice answer writing within word limits and time constraints", "Review government policies and their implications", "Study international events and their impact on India", "Practice mock interviews with diverse panels"],
                "projects": ["Create a comprehensive current affairs magazine", "Develop a study group with structured discussions", "Write detailed notes on complete UPSC syllabus", "Mentor other UPSC aspirants through online platforms"]
            },
            
            # Professional Skills
            "fitness": {
                "topics": ["Exercise Physiology", "Workout Planning", "Strength Training", "Cardiovascular Fitness", "Flexibility and Mobility", "Nutrition Basics", "Weight Management", "Injury Prevention", "Recovery and Rest", "Goal Setting", "Progress Tracking", "Equipment Usage", "Home Workouts", "Gym Etiquette", "Mental Health Benefits", "Sport-Specific Training", "Functional Fitness", "Balance and Coordination", "Endurance Building", "Lifestyle Integration"],
                "practical_tasks": ["Complete a 30-minute full-body workout targeting all major muscle groups", "Track daily food intake and calculate macronutrient ratios", "Learn proper form for 10 essential exercises (squats, push-ups, deadlifts, etc.)", "Complete a 5km run/walk and track time improvement", "Practice yoga or stretching routine for flexibility", "Plan and prep healthy meals for the entire week", "Measure body composition and fitness metrics monthly", "Try a new fitness activity (dance, martial arts, swimming)", "Complete a high-intensity interval training (HIIT) session", "Practice meditation or mindfulness for mental fitness"],
                "projects": ["Design a 12-week personal fitness transformation program", "Train for and complete a local 5K or 10K race", "Create and share fitness content on social media", "Achieve a specific fitness goal (pull-ups, marathon, weight loss)"]
            },
            "weight_loss": {
                "topics": ["Caloric Deficit Fundamentals", "Macronutrient Balance", "Meal Planning and Prep", "Portion Control Techniques", "Healthy Food Substitutions", "Cardio Exercise Planning", "Strength Training for Fat Loss", "Metabolism and BMR Understanding", "Hydration and Weight Loss", "Sleep Quality Impact", "Stress Management", "Progress Tracking Methods", "Plateaus and Solutions", "Sustainable Lifestyle Changes", "Emotional Eating Management", "Social Situations Navigation", "Long-term Maintenance", "Body Composition vs Scale Weight", "Supplementation Basics", "Medical Considerations"],
                "practical_tasks": ["Calculate your daily caloric needs and create a 500-calorie deficit plan", "Track all food intake for 7 days using a nutrition app with accurate weighing", "Plan and prep 21 healthy meals for the week with proper portion sizes", "Complete 4 cardio sessions this week: 2 HIIT and 2 steady-state sessions", "Learn to read nutrition labels and identify hidden calories in processed foods", "Replace 3 high-calorie foods with healthier alternatives in your regular diet", "Create a strength training routine targeting all major muscle groups 3x per week", "Establish a consistent sleep schedule of 7-9 hours to support weight loss", "Practice mindful eating techniques during 3 meals to improve portion awareness", "Take body measurements and progress photos in addition to weighing yourself"],
                "projects": ["Lose 1-2 pounds per week consistently for your target duration", "Create a personalized cookbook with 50 healthy, low-calorie recipes", "Document your weight loss journey through photos and measurements", "Build sustainable habits that maintain weight loss long-term"]
            },
            "cooking": {
                "topics": ["Kitchen Safety and Hygiene", "Basic Cooking Techniques", "Knife Skills", "Understanding Ingredients", "Flavor Pairing", "International Cuisines", "Baking Fundamentals", "Meal Planning", "Nutrition and Health", "Food Storage", "Kitchen Equipment", "Recipe Development", "Presentation Skills", "Cost-Effective Cooking", "Dietary Restrictions", "Preservation Techniques", "Fermentation", "Grilling and BBQ", "Dessert Making", "Professional Cooking"],
                "practical_tasks": ["Master knife skills by practicing julienne, dice, and chiffonade cuts", "Cook one dish from a different cuisine each week", "Bake bread from scratch using only basic ingredients", "Learn to cook perfect rice, pasta, and eggs using different methods", "Create a week's worth of meal prep in one cooking session", "Practice cooking without recipes using taste and intuition", "Learn food safety by properly storing and handling different ingredients", "Cook a complete three-course meal for friends or family", "Master one cooking technique thoroughly (grilling, braising, sautéing)", "Create your own spice blends and seasoning mixtures"],
                "projects": ["Document family recipes with photos and stories", "Start a cooking blog or YouTube channel", "Cater a small event or dinner party", "Complete a culinary challenge (30 recipes in 30 days)"]
            }
        }